name: Android CI/CD
description: 'An awesome Android CI/CD pipeline for any android project.'
icon: box
color: green

on:
  push:
    branches: 
     - '*' 
     - '!master' 
     - '!release*'
  pull_request:
    branches:
     - '*' 
     - '!master' 
     - '!release*'
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace
